/* ============================================================
   FAQ data — shared across support pages
   ============================================================ */

const faqData = [
  { id:'mn-g-1', product:'masternotes', category:'general', categoryZh:'一般問題', categoryEn:'General',
    questionZh:'什麼是 Masternotes（大師說）？', questionEn:'What is Masternotes?',
    answerZh:'Masternotes 是一款古典音樂 AI 應用，讓你以對話方式探索作曲家、作品與音樂知識。',
    answerEn:'Masternotes is a classical music AI app that lets you explore composers, works, and musical knowledge through natural conversation.' },
  { id:'mn-g-2', product:'masternotes', category:'general', categoryZh:'一般問題', categoryEn:'General',
    questionZh:'Masternotes 支援哪些平台？', questionEn:'What platforms does Masternotes support?',
    answerZh:'目前支援 iOS 16 以上裝置。', answerEn:'Masternotes currently supports iOS 16 and above.' },
  { id:'mn-g-3', product:'masternotes', category:'general', categoryZh:'一般問題', categoryEn:'General',
    questionZh:'如何下載 Masternotes？', questionEn:'How do I download Masternotes?',
    answerZh:'可在 App Store 搜尋「Masternotes」或「大師說」下載。', answerEn:'Search for "Masternotes" on the App Store to download.' },
  { id:'mn-g-4', product:'masternotes', category:'general', categoryZh:'一般問題', categoryEn:'General',
    questionZh:'Masternotes 是免費的嗎？', questionEn:'Is Masternotes free to use?',
    answerZh:'Masternotes 提供免費試用，完整功能需訂閱付費方案。', answerEn:'Masternotes offers a free trial. A subscription is required for full access.' },
  { id:'mn-g-5', product:'masternotes', category:'general', categoryZh:'一般問題', categoryEn:'General',
    questionZh:'Masternotes 支援哪些語言？', questionEn:'What languages does Masternotes support?',
    answerZh:'目前支援繁體中文與英文。', answerEn:'Masternotes currently supports Traditional Chinese and English.' },
  { id:'mn-g-6', product:'masternotes', category:'general', categoryZh:'一般問題', categoryEn:'General',
    questionZh:'我的資料和對話記錄安全嗎？', questionEn:'Is my data and conversation history secure?',
    answerZh:'我們重視你的隱私，資料處理方式詳見我們的隱私政策。', answerEn:'We take your privacy seriously. Please refer to our Privacy Policy for details.' },
  { id:'mn-s-1', product:'masternotes', category:'subscription', categoryZh:'帳號與訂閱', categoryEn:'Account & Subscription',
    questionZh:'Masternotes 有哪些訂閱方案？', questionEn:'What subscription plans does Masternotes offer?',
    answerZh:'Masternotes 提供免費版及進階訂閱方案，詳情請見 App 內。', answerEn:'Masternotes offers a free tier and a premium subscription. See the app for details.' },
  { id:'mn-s-2', product:'masternotes', category:'subscription', categoryZh:'帳號與訂閱', categoryEn:'Account & Subscription',
    questionZh:'如何升級至付費方案？', questionEn:'How do I upgrade to a paid plan?',
    answerZh:'在 App 內前往「設定 → 訂閱」即可升級。', answerEn:'Go to Settings → Subscription in the app to upgrade.' },
  { id:'mn-s-3', product:'masternotes', category:'subscription', categoryZh:'帳號與訂閱', categoryEn:'Account & Subscription',
    questionZh:'如何取消訂閱？', questionEn:'How do I cancel my subscription?',
    answerZh:'可透過 App Store 的訂閱管理頁面取消訂閱。', answerEn:'You can cancel through the App Store subscription management page.' },
  { id:'mn-s-4', product:'masternotes', category:'subscription', categoryZh:'帳號與訂閱', categoryEn:'Account & Subscription',
    questionZh:'取消訂閱後還能繼續使用嗎？', questionEn:'Can I still use Masternotes after cancelling?',
    answerZh:'取消後可繼續使用至當期結束，到期後將回復免費版功能。', answerEn:'You can continue using Masternotes until the end of your billing period, then it reverts to the free tier.' },
  { id:'mn-s-5', product:'masternotes', category:'subscription', categoryZh:'帳號與訂閱', categoryEn:'Account & Subscription',
    questionZh:'訂閱可以在多台裝置上使用嗎？', questionEn:'Can I use my subscription on multiple devices?',
    answerZh:'同一 Apple ID 登入的裝置均可使用。', answerEn:'Yes, any device signed in with the same Apple ID can access your subscription.' },
  { id:'mn-s-6', product:'masternotes', category:'subscription', categoryZh:'帳號與訂閱', categoryEn:'Account & Subscription',
    questionZh:'我的付款資訊安全嗎？', questionEn:'Is my payment information secure?',
    answerZh:'所有付款均透過 Apple 處理，我們不儲存任何付款資訊。', answerEn:'All payments are processed by Apple. We do not store any payment information.' },
];
